name: rawr
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  http: ^1.5.0
  fl_chart: 1.1.1
  cupertino_icons: ^1.0.8
  mobile_scanner: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/BG.png
    - assets/logo.png
    - assets/redlogo.png
    - assets/Mastercard.png
    - assets/Paypal.png
    - assets/visa-logo.png
    - assets/cash.png
    - assets/coin.png
    - assets/profile.png
    - assets/qr-red.png
    - assets/scan-qr.png
    - assets/x-sign.png
    - assets/icons/cash.png
    - assets/icons/check-sign.png
    - assets/icons/coin.png
    - assets/icons/history-red.png
    - assets/icons/history-white.png
    - assets/icons/home-red.png
    - assets/icons/home-white.png
    - assets/icons/logo-red.png
    - assets/icons/logo.png
    - assets/icons/profile.png
    - assets/icons/qr-red.png
    - assets/icons/qr-white.png
    - assets/icons/scan-qr.png
    - assets/icons/user-circle-single.png
    - assets/icons/user-multiple.png
    - assets/icons/x-sign.png
